### ISSUE TITLE
What theme are you using on the screenshot?

### ISSUE THREAD

**Issue by gitadept** [tallpants/vscode-theme-iterm2#2]

**Comment by tallpants** [comment]
For the titlebar? That was the dark theme that iTerm 2 had before Mojave -- now it uses the regular Mojave dark titlebar.

**Comment by gitadept** [comment]
No-no, I want to get these arrows ;)
![image](https://user-images.githubusercontent.com/4085846/52777643-58b32680-3055-11e9-9fcc-f81005351c40.png)

**Comment by tallpants** [comment]
Oh! That's the default zsh prompt that comes with Prezto -- https://github.com/sorin-ionescu/prezto
